DECLARE
    V_SALARIO_MEDIO EMPLOYEES.SALARY%TYPE;
    V_SALARIO_MAXIMO EMPLOYEES.SALARY%TYPE;
    V_SALARIO_MINIMO EMPLOYEES.SALARY%TYPE;
        
    NOMBRE EMPLOYEES.FIRST_NAME%TYPE;
    APELLIDO EMPLOYEES.LAST_NAME%TYPE;
    
BEGIN
    SELECT AVG(SALARY), MAX(SALARY), MIN(SALARY) INTO V_SALARIO_MEDIO, V_SALARIO_MAXIMO, V_SALARIO_MINIMO FROM EMPLOYEES;
    
    SELECT FIRST_NAME, LAST_NAME, SALARY INTO NOMBRE, APELLIDO, V_SALARIO_MINIMO
    FROM EMPLOYEES
    WHERE SALARY = V_SALARIO_MINIMO AND ROWNUM<=1; --ME QUEDO CON EL 1 DE LOS EMPLE CON SALARIO MIN
                        
    DBMS_OUTPUT.PUT_LINE('SALARIO MEDIO: ' || V_SALARIO_MEDIO || '€' );
    DBMS_OUTPUT.PUT_LINE('SALARIO MAXIMO: ' || V_SALARIO_MAXIMO || '€');
    DBMS_OUTPUT.PUT_LINE(NOMBRE || ' ' || APELLIDO || 'TIENE EL SALARIO MINIMO: ' || V_SALARIO_MINIMO || '€');
    
EXCEPTION
    WHEN OTHERS THEN 
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20000, 'ERROR DE LA APP');
    
END;



/*DECLARE
    v_salario_medio employees.salary%TYPE;
    v_salario_maximo employees.salary%TYPE;
    v_salario_minimo employees.salary%TYPE;
    
    nombre employees.first_name%TYPE;
    apellido employees.last_name%TYPE;
BEGIN
    SELECT AVG(SALARY), MAX(SALARY),MIN(SALARY) INTO V_SALARIO_MEDIO, V_SALARIO_MAXIMO,V_SALARIO_MINIMO FROM EMPLOYEES;
    
    SELECT FIRST_NAME, LAST_NAME, SALARY INTO NOMBRE, APELLIDO, V_SALARIO_MINIMO FROM EMPLOYEES
    WHERE SALARY = V_SALARIO_MINIMO AND ROWNUM<=1;
    --ME QUEDO SOLO CON EL 1º DE LOS EMPLEADOS CON SALARIO MIN
    
    DBMS_OUTPUT.PUT_LINE('Salario medio: ' || V_salario_medio||'€');
    DBMS_OUTPUT.PUT_LINE('Salario maximo: ' || V_salario_maximo||'€');
    DBMS_OUTPUT.PUT_LINE(NOMBRE || ' ' || APELLIDO || ' tiene el salario min: ' || V_salario_minimo||'€');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR (-20000, 'ERROR');
END;*/
    